/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
 * Generated on: 01-Apr-2024 11:22:57
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.1378351301,              0,              0 
  },
  {
                1,    -1.72236371,              1 
  },
  {
     0.0714597851,              0,              0 
  },
  {
                1,   -0.603767097,              1 
  },
  {
   0.001607726095,              0,              0 
  },
  {
                1,   -1.840732336,              1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.935360193,    0.949359715 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.923861861,    0.927097857 
  },
  {
                1,              0,              0 
  },
  {
                1,    -1.95808816,   0.9823024273 
  },
  {
                1,              0,              0 
  }
};
