/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
 * Generated on: 31-Mar-2024 11:14:20
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
      2.630279541,              0,              0 
  },
  {
                1,     -1.9988451,              1 
  },
  {
      24.97149277,              0,              0 
  },
  {
                1,   -1.999839306,              1 
  },
  {
    0.01047242898,              0,              0 
  },
  {
                1,   -1.997923136,              1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.912399292,   0.9353997111 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.578231454,   0.6612762213 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.972690463,   0.9865694642 
  },
  {
                1,              0,              0 
  }
};
