/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
 * Generated on: 07-Apr-2024 11:23:38
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 9
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.4693575203,              0,              0 
  },
  {
                1,  -0.5156747699,              1 
  },
  {
     0.4415493309,              0,              0 
  },
  {
                1,   0.1789565384,              1 
  },
  {
     0.5269703269,              0,              0 
  },
  {
                1,    1.600605965,              1 
  },
  {
   0.002228523372,              0,              0 
  },
  {
                1,  -0.7519086599,              1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.411124349,   0.8805828691 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.539075613,    0.787504971 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.658002019,   0.7141805291 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.356451392,   0.9622318149 
  },
  {
                1,              0,              0 
  }
};
