/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 19-Mar-2024 13:01:38
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 9
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,2,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.1267940104,              0,              0 
  },
  {
                1,  -0.8529347181,              1 
  },
  {
     0.3012519181,              0,              0 
  },
  {
                1,   -0.554233849,              1 
  },
  {
    0.07211488485,              0,              0 
  },
  {
                1,   0.4678267241,              1 
  },
  {
     0.3880141079,              0,              0 
  },
  {
                1,              1,              0 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,2,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.350549579,   0.9534475803 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.411916137,   0.8474559188 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.546712995,   0.7246800065 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.8127936721,              0 
  },
  {
                1,              0,              0 
  }
};
