/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 19-Mar-2024 13:02:02
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.7011201382,              0,              0 
  },
  {
                1,   -1.781079054,              1 
  },
  {
     0.7011201382,              0,              0 
  },
  {
                1,   -1.783381104,              1 
  },
  {
      1.956099153,              0,              0 
  },
  {
                1,   -1.782232881,              1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.760911942,   0.9920264482 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.788931131,   0.9924885631 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.727466941,   0.9385423064 
  },
  {
                1,              0,              0 
  }
};
