/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 19-Mar-2024 13:00:16
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,2,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.2996918261,              0,              0 
  },
  {
                1,   -1.997951627,              1 
  },
  {
     0.9364651442,              0,              0 
  },
  {
                1,   -1.999178529,              1 
  },
  {
      2.758696556,              0,              0 
  },
  {
                1,             -1,              0 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,2,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.966853738,    0.980713129 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.858240604,   0.8868506551 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.6746222973,              0 
  },
  {
                1,              0,              0 
  }
};
